[package]
name = "jsonserde"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# 启用serde的 `derive` 特性。
serde = { version = "1.0.140",features = ["derive"] }
serde_json = "1.0.82"
